@echo off
echo 🏁 Launching OptiRH Development Environment...

REM Start the dev servers in a secondary window to keep output organized
echo ⏳ Starting background compilers (Vite + TSC)...
start cmd /k "npm run dev"

echo ⏳ Waiting for dev servers to warm up (10s)...
timeout /t 10 /nobreak > nul

echo 🚀 Launching Electron Shell...
call npm start
